### PR TITLE
Additional changes in tests and requirements 

### PR DESCRIPTION
**Pull request by KeimaShikai**
Made additional changes according to @allburov 's comments on previous pull requests.
I believe that at first the pipeline will fall, but we will find a competent solution for dependencies in the local CI.

Additional info: 
previously I also locked: 
* pyyaml==5.1
* Jinja2==2.10
* requests==2.21

### CODE REVIEW

**Comment by KeimaShikai** [comment]
I would suggest provide python version dependent requirements.txt and add something like into **.travic.ci**:
```yaml
language: python
jobs:
  include:
  - python: "3.4"
    env: TEST_SUITE="3.4"
  - python: "3.5"
    env: TEST_SUITE="3.5"
  - python: "3.6"
    env: TEST_SUITE="3.6"
  - python: "3.7"
    env: TEST_SUITE="3.7"
script: if [ "$TEST_SUITE" = "3.4" ]; then pip install -r 'smth'; else pip install -r 'smth_else'; fi
```
...since:
* several additional locks are required (see description);
* not all of these locks are needed for Python 3.4 

P.S.: I know that command syntax for script is wrong. It's just an example.

**Comment by allburov** [comment]
May be [environment markers](https://stackoverflow.com/a/33451105/6753144) will help us?

```
pyyaml<5.1,python_version < '3.5'
pyyaml>=5.1,python_version >='3.5'
```
Or it won't work as I've suppose?)

**Comment by KeimaShikai** [comment]
"The plan is simple, and therefore - beautiful" (c) :)
If I had known about their (markers) existence up to this point... 
It seems that before learning the basic DevOps tools - I need to deal with my python knowledge...

**Comment by KeimaShikai** [comment]
Thanks again for the tips ^^

**Pull request merged**
